### ISSUE TITLE
Firefox install fail, might require a retry

### ISSUE THREAD

**Issue by vladikoff** [mozilla-services/fxa-testing-e2e#9]
Got log from circle ci: 

```
./setup.sh
+ rm -rf ./firefox
+ rm -rf ./venv_modules
+ virtualenv venv_modules
New python executable in /home/ubuntu/fxa-testing-e2e/venv_modules/bin/python2.7
Also creating executable in /home/ubuntu/fxa-testing-e2e/venv_modules/bin/python
Installing setuptools, pip, wheel...done.
+ source venv_modules/bin/activate
++ deactivate nondestructive
++ unset -f pydoc
++ '[' -z '' ']'
++ '[' -z '' ']'
++ '[' -n /bin/bash ']'
++ hash -r
++ '[' -z '' ']'
++ unset VIRTUAL_ENV
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/home/ubuntu/fxa-testing-e2e/venv_modules
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/home/ubuntu/.yarn/bin:/opt/circleci/nodejs/v4.2.6/bin:/opt/google-cloud-sdk/bin:/home/ubuntu/virtualenvs/venv-system/bin:/opt/ghc/8.0.1/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:/home/ubuntu/.composer/vendor/bin:/opt/circleci/.phpenv/shims:/opt/circleci/.phpenv/bin:/opt/circleci/.rvm/gems/ruby-2.2.6/bin:/opt/circleci/.rvm/gems/ruby-2.2.6@global/bin:/opt/circleci/.rvm/rubies/ruby-2.2.6/bin:/home/ubuntu/.go_workspace/bin:/usr/local/go/bin:/opt/circleci/nodejs/v4.2.6/bin:/opt/circleci/.pyenv/shims:/opt/circleci/.pyenv/bin:/usr/local/android-sdk-linux/platform-tools:/usr/local/android-sdk-linux/tools:/usr/local/apache-maven/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/gradle-1.10/bin:/opt/circleci/.rvm/bin:/opt/circleci/.rvm/bin
++ PATH=/home/ubuntu/fxa-testing-e2e/venv_modules/bin:/home/ubuntu/.yarn/bin:/opt/circleci/nodejs/v4.2.6/bin:/opt/google-cloud-sdk/bin:/home/ubuntu/virtualenvs/venv-system/bin:/opt/ghc/8.0.1/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:/home/ubuntu/.composer/vendor/bin:/opt/circleci/.phpenv/shims:/opt/circleci/.phpenv/bin:/opt/circleci/.rvm/gems/ruby-2.2.6/bin:/opt/circleci/.rvm/gems/ruby-2.2.6@global/bin:/opt/circleci/.rvm/rubies/ruby-2.2.6/bin:/home/ubuntu/.go_workspace/bin:/usr/local/go/bin:/opt/circleci/nodejs/v4.2.6/bin:/opt/circleci/.pyenv/shims:/opt/circleci/.pyenv/bin:/usr/local/android-sdk-linux/platform-tools:/usr/local/android-sdk-linux/tools:/usr/local/apache-maven/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/gradle-1.10/bin:/opt/circleci/.rvm/bin:/opt/circleci/.rvm/bin
++ export PATH
++ '[' -z '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ '[' x '!=' x ']'
+++ basename /home/ubuntu/fxa-testing-e2e/venv_modules
++ PS1='(venv_modules) '
++ export PS1
++ alias pydoc
++ '[' -n /bin/bash ']'
++ hash -r
+ pip install -U pip
Requirement already up-to-date: pip in ./venv_modules/lib/python2.7/site-packages
+ pip install -r requirements.txt --no-cache-dir
Collecting jsmin==2.2.1 (from -r requirements.txt (line 1))
  Downloading jsmin-2.2.1.tar.gz
Collecting mohawk==0.3.3 (from -r requirements.txt (line 2))
  Downloading mohawk-0.3.3-py2-none-any.whl
Collecting mozbuild==0.2 (from -r requirements.txt (line 3))
  Downloading mozbuild-0.2-py2-none-any.whl (373kB)
    100% |████████████████████████████████| 378kB 8.4MB/s 
Collecting mozdownload==1.21 (from -r requirements.txt (line 4))
  Downloading mozdownload-1.21-py2-none-any.whl
Collecting mozfile==1.2 (from -r requirements.txt (line 5))
  Downloading mozfile-1.2.tar.gz
Collecting mozinfo==0.9 (from -r requirements.txt (line 6))
  Downloading mozinfo-0.9.tar.gz
Collecting mozInstall==1.12 (from -r requirements.txt (line 7))
  Downloading mozInstall-1.12.tar.gz
Collecting progressbar==2.2 (from -r requirements.txt (line 8))
  Downloading progressbar-2.2.tar.gz
Collecting redo==1.5 (from -r requirements.txt (line 9))
  Downloading redo-1.5-py2.py3-none-any.whl
Collecting requests==2.9.1 (from -r requirements.txt (line 10))
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 501kB 11.6MB/s 
Collecting requests-hawk==1.0.0 (from -r requirements.txt (line 11))
  Downloading requests_hawk-1.0.0-py2.py3-none-any.whl
Collecting six==1.10.0 (from -r requirements.txt (line 12))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting treeherder-client==3.0.0 (from -r requirements.txt (line 13))
  Downloading treeherder_client-3.0.0-py2-none-any.whl
Installing collected packages: jsmin, six, mohawk, mozfile, mozbuild, redo, mozinfo, requests, requests-hawk, treeherder-client, progressbar, mozdownload, mozInstall
  Running setup.py install for jsmin ... - done
  Running setup.py install for mozfile ... - done
  Running setup.py install for mozinfo ... - done
  Running setup.py install for progressbar ... - done
  Running setup.py install for mozInstall ... - done
Successfully installed jsmin-2.2.1 mohawk-0.3.3 mozInstall-1.12 mozbuild-0.2 mozdownload-1.21 mozfile-1.2 mozinfo-0.9 progressbar-2.2 redo-1.5 requests-2.9.1 requests-hawk-1.0.0 six-1.10.0 treeherder-client-3.0.0
+ mozdownload --type=daily --destination=firefox
INFO | Retrieving the build status file from https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/
INFO | Retrieving list of builds from https://archive.mozilla.org/pub/firefox/nightly/2017/01/
INFO | Found 1 build: 2017-01-17-03-02-18-mozilla-central
INFO | Selected build: 2017-01-17-03-02-18-mozilla-central
INFO | Downloading from: https://archive.mozilla.org/pub/firefox/nightly/2017/01/2017-01-17-03-02-18-mozilla-central/firefox-53.0a1.en-US.linux-x86_64.tar.bz2
INFO | Saving as: /home/ubuntu/fxa-testing-e2e/firefox/2017-01-17-03-02-18-mozilla-central-firefox-53.0a1.en-US.linux-x86_64.tar.bz2
100% |###############################################| Time: 00:00:31   1.94 M/s
+ mozinstall firefox/2017-01-17-03-02-18-mozilla-central-firefox-53.0a1.en-US.linux-x86_64.tar.bz2 -d firefox
Traceback (most recent call last):
  File "/home/ubuntu/fxa-testing-e2e/venv_modules/bin/mozinstall", line 11, in <module>
    load_entry_point('mozInstall==1.12', 'console_scripts', 'mozinstall')()
  File "/home/ubuntu/fxa-testing-e2e/venv_modules/lib/python2.7/site-packages/mozinstall/mozinstall.py", line 315, in install_cli
    install_path = install(src, options.dest)
  File "/home/ubuntu/fxa-testing-e2e/venv_modules/lib/python2.7/site-packages/mozinstall/mozinstall.py", line 115, in install
    install_dir = mozfile.extract(src, dest)[0]
  File "/home/ubuntu/fxa-testing-e2e/venv_modules/lib/python2.7/site-packages/mozfile/mozfile.py", line 103, in extract
    namelist = extract_tarball(src, dest)
  File "/home/ubuntu/fxa-testing-e2e/venv_modules/lib/python2.7/site-packages/mozfile/mozfile.py", line 38, in extract_tarball
    namelist = bundle.getnames()
  File "/opt/circleci/python/2.7.11/lib/python2.7/tarfile.py", line 1844, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "/opt/circleci/python/2.7.11/lib/python2.7/tarfile.py", line 1836, in getmembers
    self._load()        # all members, we first have to
  File "/opt/circleci/python/2.7.11/lib/python2.7/tarfile.py", line 2416, in _load
    tarinfo = self.next()
  File "/opt/circleci/python/2.7.11/lib/python2.7/tarfile.py", line 2347, in next
    self.fileobj.seek(self.offset - 1)
mozinstall.mozinstall.InstallError: Failed to install "/home/ubuntu/fxa-testing-e2e/firefox/2017-01-17-03-02-18-mozilla-central-firefox-53.0a1.en-US.linux-x86_64.tar.bz2 (compressed file ended before the logical end-of-stream was detected)"

./setup.sh returned exit code 1

Action failed: ./setup.sh
```

**Comment by vladikoff** [comment]
Closing this until we see it again...
